In [1]:
from pathlib import Path
import pandas as pd

station_file = Path("data/raw/stations/hly3723_subset.csv")

# The first 41 lines describe the station; line 42 contains column names.
station = pd.read_csv(station_file, skiprows=41, nrows=5)

print("Columns:", station.columns.tolist())
display(station)

Columns: ['date', 'ind', 'rain', 'ind.1', 'temp', 'ind.2', 'wetb', 'dewpt', 'vappr', 'rhum', 'msl', 'ind.3', 'wdsp', 'ind.4', 'wddir', 'ww', 'w', 'sun', 'vis', 'clht', 'clamt']

,date,ind,rain,ind.1,temp,ind.2,wetb,dewpt,vappr,rhum,...,ind.3,wdsp,ind.4,wddir,ww,w,sun,vis,clht,clamt
0,01-jan-2024 00:00,111,0.0,111,5.5,111,-49.0,3.5,7.9,87,...,111,19,111,240,1,81,0.0,20000,999,1
1,01-jan-2024 01:00,111,0.0,111,5.0,111,4.1,2.9,7.5,86,...,111,16,111,240,2,11,0.0,20000,999,1
2,01-jan-2024 02:00,111,0.0,111,4.6,111,3.7,2.3,7.2,85,...,111,17,111,240,2,11,0.0,20000,999,1
3,01-jan-2024 03:00,111,0.0,111,4.1,111,3.3,2.0,7.1,87,...,111,15,111,240,2,11,0.0,20000,999,1
4,01-jan-2024 04:00,111,0.0,111,4.6,111,3.6,2.2,7.1,84,...,111,15,111,230,2,11,0.0,20000,999,1

In [2]:
# Read all hourly records for this station
station = pd.read_csv(station_file, skiprows=41)

print("Number of rows:", len(station))
print("Column names:", station.columns.tolist())

# Look at the date, rainfall, and its indicator
display(station[["date", "ind", "rain"]].head(10))
print("Rainfall indicator values:")
print(station["ind"].value_counts(dropna=False))

Number of rows: 8784
Column names: ['date', 'ind', 'rain', 'ind.1', 'temp', 'ind.2', 'wetb', 'dewpt', 'vappr', 'rhum', 'msl', 'ind.3', 'wdsp', 'ind.4', 'wddir', 'ww', 'w', 'sun', 'vis', 'clht', 'clamt']

                date  ind  rain
0  01-jan-2024 00:00  111   0.0
1  01-jan-2024 01:00  111   0.0
2  01-jan-2024 02:00  111   0.0
3  01-jan-2024 03:00  111   0.0
4  01-jan-2024 04:00  111   0.0
5  01-jan-2024 05:00  111   0.0
6  01-jan-2024 06:00  111   0.0
7  01-jan-2024 07:00  111   0.0
8  01-jan-2024 08:00  111   0.0
9  01-jan-2024 09:00  111   0.0

Rainfall indicator values:
ind
111    8784
Name: count, dtype: int64

In [3]:
print("Rainfall indicator counts:")
print(station["ind"].value_counts(dropna=False))

print("\nRainfall values:")
print(station["rain"].describe())

print("\nHours with rainfall above zero:")
print((station["rain"] > 0).sum())

Rainfall indicator counts:
ind
111    8784
Name: count, dtype: int64

Rainfall values:
count    8784.000000
mean        0.076332
std         0.331329
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         8.300000
Name: rain, dtype: float64

Hours with rainfall above zero:
1183

In [4]:
# Print the station notes at the top of the CSV
with open(station_file, encoding="utf-8") as file:
    for line_number in range(1, 42):
        line = file.readline()
        print(f"{line_number}: {line.rstrip()}")

1: Station Name: CASEMENT
2: Station Height: 91 M
3: Latitude:53.306  ,Longitude: -6.439
4:
5:
6: date:  -  Date and Time (utc)
7: ind:   -  irainfall   Rainfall indicator
8: rain:  -  Precipitation Amount (mm)
9: ind:   -  ittt Dry bulb indicator
10: temp:  -  Air Temperature (C)
11: ind:   -  iwb Wet bulb indicator
12: wetb:  -  Wet Bulb Temperature (C)
13: dewpt: -  Dew Point Temperature (C)
14: rhum:  -  Relative Humidity (%)
15: vappr: -  Vapour Pressure (hPa)
16: msl:   -  Mean Sea Level Pressure (hPa)
17: ind:   -  itabspeed wind Speed indicator
18: wdsp:  -  Mean Wind Speed (knot)
19: ind:   -  itabdir  wind dir indicator
20: wddir: -  Predominant Wind Direction (degree)
21: ww:    -  Synop code for Present Weather
22: w:     -  Synop code for Past Weather
23: sun:   -  Sunshine duration (hours)
24: vis:   -  Visibility (m)
25: clht:  -  Cloud height (100's of ft) - 999 if none
26: clamt: -  Cloud amount
27:
28:
29: Code  irainfall                    ittt              iwb                    itabspeed / itabdir
30: ----  -------------------------    --------------    ---------------------  -------------------------
31: 0     satisfactory                 positive          positive               -
32: 1     deposition                   negative          negative               10 min
33: 2     trace / sum of traces        est. positive     est. positive          60 min
34: 3     trace / sum of traces (dep.) est. negative     est. negative          10 min + defective
35: 4     estimated precipitation      not available     not available          60 min + defective
36: 5     estimated deposition         -                 frozen negative        10 min + partially defective
37: 6     estimated precip. trace      -                 frozen positive        60 min + partially defective
38: 7     estimated deposition trace   -                 est. frozen negative   not available
39: 8     not available                -                 est. frozen positive   -
40: 111   investigation required       investigation required                   investigation required
41:

In [6]:
station_files = [
    "hly3904_subset.csv",
    "hly518_subset.csv",
    "hly4935_subset.csv",
    "hly532.csv",
]

for filename in station_files:
    path = Path("data/raw/stations") / filename
    other_station = pd.read_csv(path, skiprows=41)

    # Dublin's file also contains years outside 2024
    rows_2024 = other_station[
        other_station["date"].str.contains("-2024 ", na=False)
    ]

    print(f"\n{filename}: {len(rows_2024)} rows in 2024")
    print(rows_2024["ind"].value_counts(dropna=False))

hly3904_subset.csv: 8784 rows in 2024
ind
111    8784
Name: count, dtype: int64

hly518_subset.csv: 8784 rows in 2024
ind
111    8784
Name: count, dtype: int64

hly4935_subset.csv: 8784 rows in 2024
ind
111    8784
Name: count, dtype: int64

C:\Users\engma\AppData\Local\Temp\ipykernel_38212\2737588112.py:10: DtypeWarning: Columns (8,9,14,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  other_station = pd.read_csv(path, skiprows=41)

hly532.csv: 8784 rows in 2024
ind
111    8784
Name: count, dtype: int64

In [7]:
dublin_file = Path("data/raw/stations/hly532.csv")

# Read only the columns we need; this also avoids the mixed-type warning
dublin = pd.read_csv(
    dublin_file,
    skiprows=41,
    usecols=["date", "ind", "rain"]
)

for year in [2023, 2024]:
    rows = dublin[dublin["date"].str.contains(f"-{year} ", na=False)]
    print(f"\nDublin {year}: {len(rows)} rows")
    print(rows["ind"].value_counts(dropna=False).head())

Dublin 2023: 8760 rows
ind
111    8760
Name: count, dtype: int64

Dublin 2024: 8784 rows
ind
111    8784
Name: count, dtype: int64

In [9]:
station["date"] = pd.to_datetime(
    station["date"],
    format="%d-%b-%Y %H:%M",
    utc=True
)

print("First timestamp:", station["date"].min())
print("Last timestamp:", station["date"].max())
print("Number of timestamps:", station["date"].nunique())

display(station[["date", "rain", "ind"]].head())

First timestamp: 2024-01-01 00:00:00+00:00
Last timestamp: 2024-12-31 23:00:00+00:00
Number of timestamps: 8784

                       date  rain  ind
0 2024-01-01 00:00:00+00:00   0.0  111
1 2024-01-01 01:00:00+00:00   0.0  111
2 2024-01-01 02:00:00+00:00   0.0  111
3 2024-01-01 03:00:00+00:00   0.0  111
4 2024-01-01 04:00:00+00:00   0.0  111

In [10]:
weather_columns = ["temp", "rhum", "msl", "clamt"]

display(station[["date"] + weather_columns].head(10))

print("Missing values:")
print(station[weather_columns].isna().sum())

print("\nTemperature indicator:")
print(station["ind.1"].value_counts(dropna=False))

                       date  temp  rhum    msl  clamt
0 2024-01-01 00:00:00+00:00   5.5    87  995.0      1
1 2024-01-01 01:00:00+00:00   5.0    86  995.8      1
2 2024-01-01 02:00:00+00:00   4.6    85  996.5      1
3 2024-01-01 03:00:00+00:00   4.1    87  997.2      1
4 2024-01-01 04:00:00+00:00   4.6    84  997.9      1
5 2024-01-01 05:00:00+00:00   4.0    83  998.3      1
6 2024-01-01 06:00:00+00:00   3.7    86  998.4      2
7 2024-01-01 07:00:00+00:00   4.1    85  998.7      1
8 2024-01-01 08:00:00+00:00   3.5    86  998.9      1
9 2024-01-01 09:00:00+00:00   3.6    85  999.0      3

Missing values:
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Temperature indicator:
ind.1
111    8784
Name: count, dtype: int64

In [11]:
import numpy as np

# Find the cloud file inside the data folder
cloud_file = next(Path("data").rglob("ireland_clouds_*.npz"))

# Load only its timestamps
with np.load(cloud_file) as cloud_data:
    cloud_times = pd.to_datetime(cloud_data["times"], utc=True)

print("Cloud hours:", len(cloud_times))
print("Station hours:", len(station))
print("Cloud period:", cloud_times.min(), "to", cloud_times.max())
print("Station period:", station["date"].min(), "to", station["date"].max())

matching_hours = station["date"].isin(cloud_times).sum()
print("Station hours matching cloud hours:", matching_hours)

Cloud hours: 8784
Station hours: 8784
Cloud period: 2024-01-01 00:00:00+00:00 to 2024-12-31 23:00:00+00:00
Station period: 2024-01-01 00:00:00+00:00 to 2024-12-31 23:00:00+00:00
Station hours matching cloud hours: 8784

In [12]:
# One row for each cloud image time
cloud_hours = pd.DataFrame({"date": cloud_times})

# Add Casement measurements for the same hour
casement_aligned = cloud_hours.merge(
    station[["date", "rain", "ind", "temp", "rhum", "msl", "clamt"]],
    on="date",
    how="left",
    validate="one_to_one"
)

print("Aligned rows:", len(casement_aligned))
display(casement_aligned.head())

Aligned rows: 8784

                       date  rain  ind  temp  rhum    msl  clamt
0 2024-01-01 00:00:00+00:00   0.0  111   5.5    87  995.0      1
1 2024-01-01 01:00:00+00:00   0.0  111   5.0    86  995.8      1
2 2024-01-01 02:00:00+00:00   0.0  111   4.6    85  996.5      1
3 2024-01-01 03:00:00+00:00   0.0  111   4.1    87  997.2      1
4 2024-01-01 04:00:00+00:00   0.0  111   4.6    84  997.9      1

In [13]:
print("Aligned rows:", len(casement_aligned))
print("\nMissing values after alignment:")
print(casement_aligned.isna().sum())

Aligned rows: 8784

Missing values after alignment:
date     0
rain     0
ind      0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

In [14]:
station_names = {
    "Casement": "hly3723_subset.csv",
    "Cork Airport": "hly3904_subset.csv",
    "Shannon Airport": "hly518_subset.csv",
    "Knock Airport": "hly4935_subset.csv",
    "Dublin Airport": "hly532.csv",
}

columns_to_check = ["date", "rain", "temp", "rhum", "msl", "clamt"]

for name, filename in station_names.items():
    path = Path("data/raw/stations") / filename

    data = pd.read_csv(path, skiprows=41, usecols=columns_to_check)
    data = data[data["date"].str.contains("-2024 ", na=False)]

    print(f"\n{name}: {len(data)} hours")
    print(data.isna().sum())

Casement: 8784 hours
date     0
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Cork Airport: 8784 hours
date     0
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Shannon Airport: 8784 hours
date     0
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Knock Airport: 8784 hours
date     0
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

C:\Users\engma\AppData\Local\Temp\ipykernel_38212\2335657437.py:14: DtypeWarning: Columns (9,20) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(path, skiprows=41, usecols=columns_to_check)

Dublin Airport: 8784 hours
date     0
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

In [15]:
measurements = ["rain", "temp", "rhum", "msl", "clamt"]

for name, filename in station_names.items():
    path = Path("data/raw/stations") / filename

    data = pd.read_csv(
        path,
        skiprows=41,
        usecols=["date"] + measurements,
        low_memory=False
    )
    data = data[data["date"].str.contains("-2024 ", na=False)]

    # Unreadable numbers become NaN, so we can count them
    numeric_data = data[measurements].apply(pd.to_numeric, errors="coerce")

    print(f"\n{name} — missing or non-numeric values:")
    print(numeric_data.isna().sum())

Casement — missing or non-numeric values:
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Cork Airport — missing or non-numeric values:
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Shannon Airport — missing or non-numeric values:
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Knock Airport — missing or non-numeric values:
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

Dublin Airport — missing or non-numeric values:
rain     0
temp     0
rhum     0
msl      0
clamt    0
dtype: int64

In [16]:
for name, filename in station_names.items():
    path = Path("data/raw/stations") / filename
    dates = pd.read_csv(path, skiprows=41, usecols=["date"])["date"]
    dates = dates[dates.str.contains("-2024 ", na=False)]
    dates = pd.to_datetime(dates, format="%d-%b-%Y %H:%M", utc=True)

    missing_hours = (~cloud_times.isin(dates)).sum()
    repeated_hours = dates.duplicated().sum()

    print(f"{name}: {missing_hours} missing hours, {repeated_hours} repeated hours")

Casement: 0 missing hours, 0 repeated hours
Cork Airport: 0 missing hours, 0 repeated hours
Shannon Airport: 0 missing hours, 0 repeated hours
Knock Airport: 0 missing hours, 0 repeated hours
Dublin Airport: 0 missing hours, 0 repeated hours